name: Release

on:
  push:
    branches: [ main ]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 26
      - uses: bahmutov/npm-install@v1

      - uses: changesets/action@v1
        with:
          publish: npm publish
